Use acceptable name for GitHub token secret
ryansonshine/typescript-npm-package-template pull request #10
Opened 2022-05-08 15:47 UTC by patik

### Change name for GitHub token

GitHub doesn't allow you to add a repository secret named `GITHUB_*`. This PR changes the name to `GH_TOKEN` and also adds instructions to the readme.

### Pull-Request Checklist

- [ ] Code is up-to-date with the `main` branch
- [ ] `npm run lint` passes with this change
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

2022-05-09 06:04 UTC, ryansonshine commented
Hi @patik,

Thanks for the contribution, I really appreciate it!

Per the [GitHub action docs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret):

> At the start of each workflow run, GitHub automatically creates a unique `GITHUB_TOKEN` secret to use in your workflow. You can use the `GITHUB_TOKEN` to authenticate in a workflow run.

The `GITHUB_TOKEN` environment variable is set automatically. Perhaps we could add a section in the README making a brief mention on how this doesn't need to be set manually, thoughts?

2022-05-09 06:17 UTC, ryansonshine requested changes
See previous comment

2022-05-13 07:39 UTC, sneko commented
@patik @ryansonshine I think it would be easier to directly point to this part: https://github.com/semantic-release/github#github-authentication

It explains in details which strategy to use depending on the need.

(to be honest, I struggled some time with those... thinking I had to create it manually, but was setting `GH_TOKEN` and didn't know by default `GITHUB_TOKEN` was populated... If you don't have the idea to check specifically `https://github.com/semantic-release/github` there is no way to know about right permissions to set).

At the end maybe the easiest way is to adjust the template to have in `release.yaml`: 

```
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
...
```

It will grant needed permissions automatically.

2022-05-13 08:15 UTC, ryansonshine commented
Thanks @sneko ! I agree I think an update to `release.yml` would be ideal. 

Let me know if you'd like to open a PR, otherwise I should be able to get around to this sometime in the new few days.

2022-05-20 06:32 UTC, closed without merging

2022-05-20 06:35 UTC, ryansonshine commented
Closing this PR after implementing the changes proposed in https://github.com/ryansonshine/typescript-npm-package-template/pull/10#issuecomment-1125750574 with https://github.com/ryansonshine/typescript-npm-package-template/commit/f05e389f96cf273e9df7a10af9155c40200b7b39